protected/models/Usuario.php
<?php

/**
 * This is the model class for table "tbl_users".
 *
 * The followings are the available columns in table 'tbl_users':
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $correo
 * @property string $estatus
 */
class Usuario extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, password, correo, estatus', 'required'),
			array('username', 'length', 'max'=>20),
			array('password, correo, estatus', 'length', 'max'=>30),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, password, correo, estatus , cedula', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'cedula' => 'Cedula',
			'username' => 'Nombre de Usuario',
			'password' => 'Contraseña',
			'correo' => 'Correo',
			'estatus' => 'Estatus',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('cedula',$this->cedula,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('correo',$this->correo,true);
		$criteria->compare('estatus',$this->estatus,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Usuario the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public function bloqueado($id)
	{
		$sql="SELECT estatus FROM  `tbl_users` where id='$id';";
		$estatus=yii::app()->db->createCommand($sql)->queryAll();
		if($estatus===null)
			return False;
			if ($estatus[0]["estatus" ]==='ACTIVO') return true;
			else  return False;
		
	}
	
		public static function cargar($id)
	{
		$model=Usuario::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
	
	public static function cargarCedula($cedula)
	{
            $model= Usuario::model()->find("(cedula)=?",array($cedula));		
		if($model===null)
                        return false;
		return $model;  		
	}
	

		public function buscarUltimo()
	{
		$sql="SELECT MAX(`id`) FROM  `tbl_users`;";
		$num=yii::app()->db->createCommand($sql)->queryAll();
		if($num===null)
			throw new CHttpException(404,' no se puede procesar.');
		return $num[0]["MAX(`id`)" ] + 1;
	}
		

		public function guardarUsuario($username,$password,$cedula,$correo)
	{
		$conexion=yii::app()->db;		
		$contrasenha=md5($password);
		$id=$this->buscarUltimo();

		$consulta="insert into tbl_users(id,username,password,cedula,correo,estatus)";
		$consulta .="values (".$id.",'$username','$contrasenha','$cedula','$correo','ACTIVO')";
		$resultado=$conexion->createCommand($consulta)->execute();

		$this->asignarRoleDefault($id);
		
	}

		public function asignarRoleDefault($id)
	{
		yii::app()->authManager->assign('demo',$id);//asigna el items        	
		
	}

	public function behaviors()
{
    return array(
        // Classname => path to Class
        'ActiveRecordLogableBehavior'=>
            'application.behaviors.ActiveRecordLogableBehavior',
    );
}

}

protected/controllers/UsuarioController.php
<?php

class UsuarioController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','obtenerEtiqueta','AjaxActivador',
				'ReiniciarPass','cambiarContrasena'),				
				'roles'=>array('admin'),				
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','cambiarContrasena','datos'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','asignarPermiso','Bloquear','username',),
				'roles'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$role=new RoleForm;
		
		if (isset($_POST["RoleForm"]))
		{
			$role->attributes=$_POST["RoleForm"];
			if($role->validate())
			{
				yii::app()->authManager->createRole($role->name,$role->description);
				yii::app()->authManager->assign($role->name,$id);
				$this->redirect(array("view","id"=>$id));
			}
		}		
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			'role'=>$role,//envio mi formulario
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Usuario;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Usuario']))
		{
			$model->attributes=$_POST['Usuario'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Usuario']))
		{
			$model->attributes=$_POST['Usuario'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex(){
	
		$dataProvider=new CActiveDataProvider('Usuario', array(
			'criteria'=>array(
				'condition'=>'id<>'.Yii::app()->user->getId())));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Usuario('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Usuario']))
			$model->attributes=$_GET['Usuario'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}


	public function actionAsignarPermiso($id)
	{
		foreach(yii::app()->authManager->getAuthItems() as $data)
		{

        
	        if ($data->name==$_GET["item"]){
					if(yii::app()->authManager->checkAccess($data->name,$id)) //si llega el item lo elmina	
							yii::app()->authManager->revoke($_GET["item"],$id);//lo quita
					else
							yii::app()->authManager->assign($_GET["item"],$id);//asigna el items        	
		    }else{
	        		#if(yii::app()->authManager->checkAccess($data->name,$id))//si llega el item lo elmina	
							yii::app()->authManager->revoke($data->name,$id);//lo quita			
		 
	        } 
	     }		
		$this->redirect(array("view","id"=>$id));	
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Usuario the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Usuario::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Usuario $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='usuario-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	 // en la controladora o componente:
	public function obtenerEtiqueta($model){
		#var_dump($model->attributes['estatus']);
		
		if(($model->attributes['estatus']=='ACTIVO') or ($model->attributes['estatus']==='ACTIVO')){
			return "Desactivado";
		}else{
			return "Activado";
		}
	}
	public function actionAjaxActivador($id){
		// activara al usuario en la sesion de ejemplo, pudimos haber dicho aqui:
		//   "por favor activa este usuario en la nomina seleccionada"
		
		$etiqueta = "";
		$model=Usuario::model();
		$aux=Usuario::model();
		$aux=$model::cargar($id);
		if ($aux->attributes['estatus']=='ACTIVO')#activo
		{
		$aux->updateByPk($id,array('estatus'=>'INACTIVO'));
		$etiqueta = "Activado";
		
		
		}			
		else { 
			 $aux->updateByPk($id,array('estatus'=>'ACTIVO'));
				$etiqueta = "Desactivado";
		}
		
		
		echo $etiqueta;
	}

	
	
	public function actionBloquear($id)
	{  $model=Usuario::model();
		$aux=Usuario::model();
		$aux=$model::cargar($id);
		if ($aux->attributes['estatus']=='ACTIVO')#activo
		{
		$aux->updateByPk($id,array('estatus'=>'INACTIVO'));		
		}			
		else   $aux->updateByPk($id,array('estatus'=>'ACTIVO'));	
		$this->redirect(array("view","id"=>$id));
	}
	
	public function actionDatos(){
		$Username= new UsernameForm();
		$Correo= new CorreoForm();
		

		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'UsernameForm' )
			{
			echo CActiveForm::validate($Username);
			yii::app()->end();
			}

		if (isset($_POST['ajax']) && $_POST['ajax'] === 'CorreoForm' )
			{
			echo CActiveForm::validate($Correo);
			yii::app()->end();
			}


		
		if(isset($_POST['UsernameForm']))
		{
			$Username->attributes=$_POST['UsernameForm'];
			$Username->guardarNombreUsuario();	
			$alerta= new Alerta();
			$alerta->nombre();		
			Yii::app()->user->setFlash('success','Nombre de usuario actualizado satisfactoriamente');	
		}

		if(isset($_POST['CorreoForm']))
		{
			$Correo->attributes=$_POST['CorreoForm'];
			$Correo->guardarCorreo();
			$alerta= new Alerta();
			$alerta->correo();	
			Yii::app()->user->setFlash('success','Correo actualizado satisfactoriamente');	
		}
		
		$this->render('Datos',array('Username'=>$Username,'Correo'=>$Correo,'datos'=>$d=Usuario::model()->cargarCedula(yii::app()->user->getState('cedula'))));
		
	}
	
	public function actionCambiarContrasena(){
		$model= new ContrasenaForm();
		$alerta= new Alerta();
		$msg='La contraseña ha sido cambiada';		
		$usuario=Usuario::model()->cargarCedula(yii::app()->user->getState('cedula'));
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'ContrasenaForm' )
			{
			echo CActiveForm::validate($model);
			yii::app()->end();
			}
		
		if(isset($_POST['ContrasenaForm']))
		{
			$model->attributes=$_POST['ContrasenaForm'];
			$model->guardarContrasena($model->attributes['password']);
			$alerta->cambioContrasena();
			#$this->refresh();	
			$model->passActual='';$model->password='';
			$model->repetirPassword='';
			Yii::app()->user->setFlash('success',$msg );	
		}
		
			
			$this->render('Contrasena',
		array('model'=>$model,'usuario'=>$usuario));
		
	}
	
	public function actionReiniciarPass($id)
	{
		
		$model=Usuario::model();
		$aux=Usuario::model();
		$aux=$model::cargar($id);
		$msg='La contraseña de '."$aux->username $aux->cedula".' ha sido reiniciada satisfactoriamente ';
		$contrasena=md5($aux->cedula);
		$aux->updateByPk($aux->id,array('password'=>$contrasena));
		Yii::app()->user->setFlash('notice',$msg );	
		$this->actionAdmin();
		#bandera
		#enviar notificacion usuario
		#bandera para el usurio que cambien su clave	
		
	}



		public function actionusername(){
		$model= new DatosForm();
		$msg='tus Datos han sido actualizados';
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'DatosForm' )
			{
			echo CActiveForm::validate($model);
			yii::app()->end();
			}
		
		if(isset($_POST['DatosForm']))
		{
			$model->attributes=$_POST['DatosForm'];
			#$model->guardarContrasena($model->attributes['password']);
			
			Yii::app()->user->setFlash('success',$msg );	
		}
		

protected/views/usuario/Contrasena.php
<?php
/* @var $this UsuarioController */
/* @var $model Usuario */




?>

<h1>Cambio de contraseña (<?php echo $usuario->username; ?>)</h1>

<?php $this->renderPartial('_contrasena', array('model'=>$model)); ?>


protected/views/usuario/Datos.php

<h1>Actualizar mis Datos (<?php echo $datos->username; ?>)</h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$datos,
	'attributes'=>array(		
		#'username',		
		#'correo',
		'cedula',

 array(
        'name'=>'Nombre de Usuario',
        'type'=>'raw',
          'value'=>$datos->username.' '.CHtml::link('editar', '#'
        , array( 'onclick'=>'$("#mydialog").dialog("open"); return false;',
    )),
    ),

     array(
        'name'=>'Correo',
        'type'=>'raw',
       'value'=>$datos->correo.' '.CHtml::link('editar', '#'
        , array( 'onclick'=>'$("#mydialog2").dialog("open"); return false;',
    )),
      #  'click'=>'$("#mydialog").dialog("open"); return false;',
    
    ),

	

))); ?>
<?php $this->renderPartial('_username', array('Username'=>$Username)); ?>
<?php $this->renderPartial('_correo', array('Correo'=>$Correo)); ?>

<?php
/* @var $this UsuarioController */
/* @var $model Usuario */
/* @var $form CActiveForm */
?>




protected/views/usuario/ReiniciarContrasena.php
<?php
/* @var $this UsuarioController */
/* @var $model Usuario */




?>

<h1>Cambio de contraseña (<?php echo $usuario->username; ?>)</h1>

<?php $this->renderPartial('_contrasena', array('model'=>$model)); ?>


protected/views/usuario/_contrasena.php

<div class="form"> 

<?php $form=$this->beginWidget('CActiveForm',array( 
				
				'action'=>yii::app()->createUrl('usuario/cambiarContrasena'),
				'id'=>'ContrasenaForm',
				#'enableClientValidation'=>true,
				'enableAjaxValidation'=>true,
				'clientOptions'=>array('validateOnSubmit'=>true),
				)); 
?>


	
	<?php   echo $form->errorSummary($model); ?>

	

	<div class="row">
		<?php echo $form->labelEx($model,'passActual', array('label' => 'Contraseña actual')); ?>
		<?php echo $form->passwordField($model,'passActual',array('size'=>30,'maxlength'=>30)); ?>
		<?php echo $form->error($model,'passActual'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'password', array('label' => 'Contraseña Nueva')); ?>
		<?php echo $form->passwordField($model,'password',array('size'=>30,'maxlength'=>30)); ?>
		<?php echo $form->error($model,'password'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'repetirPassword',array('label' => 'Repita Contraseña')); ?>
		<?php echo $form->passwordField($model,'repetirPassword',array('size'=>30,'maxlength'=>30)); ?>
		<?php echo $form->error($model,'repetirPassword'); ?>
	</div>
	

	<div class="row buttons">
		<?php echo CHtml::submitButton('Cambiar Contraseña'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/usuario/_correo.php
<?php
/* @var $this UsuarioController */
/* @var $model Usuario */
/* @var $form CActiveForm */
?>



<?php  $this->beginWidget('zii.widgets.jui.CJuiDialog',array(
    'id'=>'mydialog2',
    // additional javascript options for the dialog plugin
    'options'=>array(
        'title'=>'Actualizar',
        'autoOpen'=>false,
        'modal'=>true,      
        'width'=>300,
       # 'height'=>200,        
        'resizable'=>false,
        
        'overlay'=>array(
            'backgroundColor'=>'#000',
            'opacity'=>'0.5'
    ),
)));
 

    
echo "<div class='form'> ";

 $form=$this->beginWidget('CActiveForm',array( 
				
				'action'=>yii::app()->createUrl('usuario/Datos'),
				'id'=>'CorreoForm',
				#'enableClientValidation'=>true,
				'enableAjaxValidation'=>true,
				'clientOptions'=>array('validateOnSubmit'=>true),
				)); 



	echo $form->errorSummary($Correo); 

	
	echo "<div class='row'>";
		 echo $form->labelEx($Correo,'correo'); 
		 echo $form->textField($Correo,'correo',array('size'=>100,'maxlength'=>100)); 
		 echo $form->error($Correo,'correo');
	echo "</div>";

	

	echo "<div class='row buttons'>";
		 echo CHtml::submitButton('Actualizar'); 
	echo "</div>";

 $this->endWidget();

echo "</div>";

$this->endWidget('zii.widgets.jui.CJuiDialog');


?> 

protected/views/usuario/_form.php
<?php
/* @var $this UsuarioController */
/* @var $model Usuario */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'usuario-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username',array('size'=>20,'maxlength'=>20)); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php  $form->labelEx($model,'password'); ?>
		<?php  $form->passwordField($model,'password',array('size'=>30,'maxlength'=>30)); ?>
		<?php  $form->error($model,'password'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'correo'); ?>
		<?php echo $form->textField($model,'correo',array('size'=>100,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'correo'); ?>
	</div>

	<div class="row">
		<?php  $form->labelEx($model,'estatus'); ?>
		<?php  $form->textField($model,'estatus',array('size'=>30,'maxlength'=>30)); ?>
		<?php  $form->error($model,'estatus'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/usuario/index.php
<?php
/* @var $this UsuarioController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Usuarios',
);

$this->menu=array(
	#array('label'=>'Create Usuario', 'url'=>array('create')),
	array('label'=>'Administrar Usuarios', 'url'=>array('admin')),
);
?>

<h1>Usuarios</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/usuario/ppal.php
<?php
/* @var $this SiteController */

$this->pageTitle=Yii::app()->name;
$baseUrl = Yii::app()->theme->baseUrl; 
?>

<div class="row-fluid">
  <div class="span3 ">
    <div class="stat-block">
      <ul>
        <li class="stat-count"><span>Postulación</span></li>
        <li class="stat-percent"><a class="brand" href="#"><span class="text-success stat-percent">Ir</span></a></li>
      </ul>
    </div>
  </div>
  <div class="span3 ">
    <div class="stat-block">
      <ul>
        <li class="stat-count"><span>Actualizar Datos</span></li>
        <li class="stat-percent"><a class="brand" href="<?php echo yii::app()->createUrl('usuario/datos'); ?>"><span class="text-success stat-percent">Ir</span></a></li>
      </ul>
    </div>
  </div>
  <div class="span3 ">
    <div class="stat-block">
      <ul>
        <li class="stat-count"><span>Rango Ascenso</span></li>
        <li class="stat-percent"><a class="brand" href="#"><span class="text-success stat-percent">Ir</span></a></li>
      </ul>
    </div>
  </div>
  <div class="span3 ">
    <div class="stat-block">
      <ul>
        <li class="stat-count"><span>Saludo</span></li>
        <li class="stat-percent"><a class="brand" href="<?php echo yii::app()->createUrl("/Funcionarios/saludo");?>"><span><span class="text-success stat-percent">Ir</span></a></li>
      </ul>
    </div>
  </div>
</div>

<div class="row-fluid">

    
	<div class="span9">
        <img src='<?php echo $baseUrl;?>/img/big/News.png'/>
	</div>
	<div class="span3">
		<div class="summary">
          <ul>
          	<li>
          		<span class="summary-icon">
                	<img src="<?php echo $baseUrl ;?>/img/icons/Calendar.png" width="36" height="36" alt="Fecha de Postulación">
                </span>
                <span class="summary-number">Octubre 15</span>
                <span class="summary-title">Fecha de Postulación</span>
            </li>
            <li>
                <span class="summary-icon">
                    <img src="<?php echo $baseUrl ;?>/img/icons/Calendar.png" width="36" height="36" alt="Fecha de Postulación">
                </span>
                <span class="summary-number">Diciembre 12</span>
                <span class="summary-title">Fecha de Ascenso</span>
            </li>
            <li>

            </li>
            <li>

            </li>
            <li>

            </li>
        
          </ul>
        </div>

	</div>
</div>


<div class="row-fluid">
	<div class="span6">
	  
	</div><!--/span-->
	<div class="span6">

        	
	</div><!--/span-->
</div><!--/row-->

<div class="row-fluid">
	<div class="span6">
	 
	</div><!--/span-->
    <div class="span6">

    </div>
	<!--<div class="span2">
    	<input class="knob" data-width="100" data-displayInput=false data-fgColor="#5EB95E" value="35">
    </div>
	<div class="span2">
     	<input class="knob" data-width="100" data-cursor=true data-fgColor="#B94A48" data-thickness=.3 value="29">
    </div>
	<div class="span2">
         <input class="knob" data-width="100" data-min="-100" data-fgColor="#F89406" data-displayPrevious=true value="44">     	
	</div><!--/span-->
</div><!--/row-->

          


<script>
            $(function() {

                $(".knob").knob({
                    /*change : function (value) {
                        //console.log("change : " + value);
                    },
                    release : function (value) {
                        console.log("release : " + value);
                    },
                    cancel : function () {
                        console.log("cancel : " + this.value);
                    },*/
                    draw : function () {

                        // "tron" case
                        if(this.$.data('skin') == 'tron') {

                            var a = this.angle(this.cv)  // Angle
                                , sa = this.startAngle          // Previous start angle
                                , sat = this.startAngle         // Start angle
                                , ea                            // Previous end angle
                                , eat = sat + a                 // End angle
                                , r = 1;

                            this.g.lineWidth = this.lineWidth;

                            this.o.cursor
                                && (sat = eat - 0.3)
                                && (eat = eat + 0.3);

                            if (this.o.displayPrevious) {
                                ea = this.startAngle + this.angle(this.v);
                                this.o.cursor
                                    && (sa = ea - 0.3)
                                    && (ea = ea + 0.3);
                                this.g.beginPath();
                                this.g.strokeStyle = this.pColor;
                                this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sa, ea, false);
                                this.g.stroke();
                            }

                            this.g.beginPath();
                            this.g.strokeStyle = r ? this.o.fgColor : this.fgColor ;
                            this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sat, eat, false);
                            this.g.stroke();

                            this.g.lineWidth = 2;
                            this.g.beginPath();
                            this.g.strokeStyle = this.o.fgColor;
                            this.g.arc( this.xy, this.xy, this.radius - this.lineWidth + 1 + this.lineWidth * 2 / 3, 0, 2 * Math.PI, false);
                            this.g.stroke();

                            return false;
                        }
                    }
                });

                // Example of infinite knob, iPod click wheel
                var v, up=0,down=0,i=0
                    ,$idir = $("div.idir")
                    ,$ival = $("div.ival")
                    ,incr = function() { i++; $idir.show().html("+").fadeOut(); $ival.html(i); }
                    ,decr = function() { i--; $idir.show().html("-").fadeOut(); $ival.html(i); };
                $("input.infinite").knob(
                                    {
                                    min : 0
                                    , max : 20
                                    , stopper : false
                                    , change : function () {
                                                    if(v > this.cv){
                                                        if(up){
                                                            decr();
                                                            up=0;
                                                        }else{up=1;down=0;}
                                                    } else {
                                                        if(v < this.cv){
                                                            if(down){
                                                                incr();
                                                                down=0;
                                                            }else{down=1;up=0;}
                                                        }
                                                    }
                                                    v = this.cv;
                                                }
                                    });
            });
        </script>